# Hackathon #1

Written by Eleanor Quint

In [1]:
# We'll start with our library imports...
from __future__ import print_function

import tensorflow as tf  # to specify and run computation graphs

#### Tensor

The basic unit of data in TensorFlow is the [Tensor](https://www.tensorflow.org/api_docs/python/tf/Tensor). A tensor is a multi-dimensional array of numerical variable specialized for numerical computation with an underlying data type (think `float` or `int`). We say that a tensor's _rank_ is its number of dimensions. Here are some examples of tensors.

In [2]:
# a rank 0 tensor; a scalar with shape ()
its_complicated = tf.Variable(12.3 - 4.85j, tf.complex64)
print(its_complicated)

# a rank 1 tensor; a vector with shape (5,), meaning it's just a plain 'ol array
# notice that we've given a name to this variable
first_primes = tf.Variable([2, 3, 5, 7, 11], tf.int32, name='primes')
print(first_primes)

# a rank 2 tensor; a matrix with shape [2, 2]
# notice that the dtype is inferred when we don't specify it
my_identity = tf.Variable([[1, 0],[0, 1]])
print(my_identity)
print("We can retrieve a numpy array from TensorFlow as:", my_identity.numpy(), "is a", type(my_identity.numpy()))

# a rank 4 tensor with shape [10, 299, 299, 3]
blank_image = tf.zeros([10, 299, 299, 3])
print("tf.shape returns a Tensor:", tf.shape(blank_image))
print("while .shape returns a tuple:", blank_image.shape)

<tf.Variable 'Variable:0' shape=() dtype=complex128, numpy=(12.3-4.85j)>
<tf.Variable 'primes:0' shape=(5,) dtype=int32, numpy=array([ 2,  3,  5,  7, 11], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 0],
       [0, 1]], dtype=int32)>
We can retrieve a numpy array from TensorFlow as: [[1 0]
 [0 1]] is a <class 'numpy.ndarray'>
tf.shape returns a Tensor: tf.Tensor([ 10 299 299   3], shape=(4,), dtype=int32)
while .shape returns a tuple: (10, 299, 299, 3)


The rank of a tensor can be retrieved with [tf.rank](https://www.tensorflow.org/api_docs/python/tf/rank). The shape of a tensor can be retrieved by calling the [tf.shape](https://www.tensorflow.org/api_docs/python/tf/shape) operation. (Note that for a tensor $x$, `tf.rank(x) == len(tf.shape(x))`. Tensors can be reshaped with [tf.reshape](https://www.tensorflow.org/api_docs/python/tf/reshape). For example

In [4]:
print(tf.range(10))
print(tf.reshape(tf.range(10), (2,5)))  # re-arrange into two rows
print(tf.reshape(tf.range(10), (1,10))) # add a dimension

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor(
[[0 1 2 3 4]
 [5 6 7 8 9]], shape=(2, 5), dtype=int32)
tf.Tensor([[0 1 2 3 4 5 6 7 8 9]], shape=(1, 10), dtype=int32)
